name: dpaper
version: '1.0'
summary: Dynamic wallpaper changer for Kubuntu
description: |
  A C-based application for dynamically changing Kubuntu desktop wallpapers 
  with a system tray icon interface. Supports random wallpaper selection,
  time-based wallpaper changes, and application-specific wallpapers.

confinement: strict
base: core20

parts:
  c-dp-wallpaper:
    plugin: make
    source: .
    build-packages:
      - build-essential
      - libgtk-3-dev
      - libayatana-appindicator3-dev
      - libdbus-glib-1-dev
    stage-packages:
      - libgtk-3-0
      - libayatana-appindicator3-1
      - libdbus-glib-1-2

apps:
  c-dp-wallpaper:
    command: c-dp-wallpaper
    desktop: usr/share/applications/c-dp-wallpaper.desktop
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - home
      - config-kde
      - system-observe