name: dpaper
version: '1.0.1'
summary: Dynamic wallpaper changer for KDE Plasma
description: |
  A C-based application for dynamically changing KDE Plasma desktop wallpapers
  with a system tray icon interface. Features include:
  - Random wallpaper selection
  - Find and remove photos
  - 34 bundled default wallpapers
  - Auto-rotate with configurable interval
  - Per-desktop or all-desktops wallpaper setting

icon: data/icons/dpaper.png

confinement: strict
base: core22

parts:
  dpaper:
    plugin: make
    source: .
    source-type: local
    build-packages:
      - build-essential
      - libgtk-3-dev
      - libayatana-appindicator3-dev
    stage-packages:
      - libgtk-3-0
      - libayatana-appindicator3-1
      - libayatana-appindicator-glib
    stage:
      - data/

apps:
  dpaper:
    command: usr/local/bin/dpaper
    desktop: usr/share/applications/dpaper.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home